spring:
  jwt:
    secret: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D
    jwtExpirationInMs: 1800000 # 30 minute
    refresh-token:
      expiration: 604800000 # 7 days
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
urls:
  unsecured: /auth/**,/v2/api-docs,/v3/api-docs,/v3/api-docs/**,/swagger-resources,/swagger-resources/**,/configuration/ui,/configuration/security,/swagger-ui/**,/swagger-ui.html
  user: /api/v1/user/**
  book: /api/v1/book/**
